# Generated by Django 4.2.6 on 2023-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=255)),
                ('cop', models.IntegerField()),
                ('opa', models.CharField(max_length=255)),
                ('opb', models.CharField(max_length=255)),
                ('opc', models.CharField(max_length=255)),
                ('opd', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('topic_name', models.CharField(max_length=255)),
                ('choice_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
